# Generated by Django 6.0.2 on 2026-04-28 06:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='中国', max_length=50, verbose_name='国家')),
                ('state', models.CharField(db_index=True, max_length=100, verbose_name='省份')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='城市名称')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('is_domestic', models.BooleanField(default=True, verbose_name='是否国内')),
            ],
            options={
                'verbose_name': '中国城市',
                'verbose_name_plural': '中国城市',
                'db_table': 'china_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='目的地名称')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='所属城市')),
                ('location', models.CharField(max_length=200, verbose_name='地理位置')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='省份/州')),
                ('country', models.CharField(blank=True, default='中国', max_length=100, null=True, verbose_name='国家')),
                ('is_domestic', models.BooleanField(default=True, verbose_name='是否国内')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media-destination/', verbose_name='封面图片')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='media-destination/', verbose_name='展示图片1')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='media-destination/', verbose_name='展示图片2')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='media-destination/', verbose_name='展示图片3')),
                ('gallery_image_4', models.ImageField(blank=True, null=True, upload_to='media-destination/', verbose_name='展示图片4')),
                ('category', models.CharField(max_length=100, verbose_name='类别')),
                ('price_range', models.CharField(max_length=100, verbose_name='价格区间')),
                ('duration', models.CharField(max_length=100, verbose_name='游玩时长')),
                ('best_season', models.CharField(max_length=100, verbose_name='最佳季节')),
                ('features', models.JSONField(default=list, verbose_name='特色亮点')),
                ('rating', models.FloatField(default=5.0, verbose_name='评分')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('recommendation_type', models.JSONField(default=list, help_text='支持多选：default(默认推荐), nearby(IP周边推荐), managed(管理员精选), selected(出行推荐)', verbose_name='推荐类型（多选）')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '旅游目的地',
                'verbose_name_plural': '旅游目的地',
                'db_table': 'destinations',
                'ordering': ['sort_order', '-is_hot', '-rating', '-views', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='封面图片')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('publish_date', models.DateTimeField(verbose_name='发布日期')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻资讯',
                'verbose_name_plural': '新闻资讯',
                'db_table': 'news',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='政策标题')),
                ('level', models.CharField(max_length=50, verbose_name='政策级别')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('department', models.CharField(max_length=200, verbose_name='发布部门')),
                ('publish_date', models.DateTimeField(verbose_name='发布日期')),
                ('content', models.TextField(verbose_name='政策内容')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='封面图片')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='文件链接')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '政策法规',
                'verbose_name_plural': '政策法规',
                'db_table': 'policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='隐患标题')),
                ('risk_level', models.CharField(choices=[('高', '高风险'), ('中', '中风险'), ('低', '低风险')], max_length=20, verbose_name='风险等级')),
                ('category', models.CharField(max_length=100, verbose_name='隐患类别')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('prevention', models.TextField(verbose_name='预防措施')),
                ('emergency_plan', models.TextField(verbose_name='应急预案')),
                ('report_date', models.DateTimeField(verbose_name='报告日期')),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('处理中', '处理中'), ('已解决', '已解决')], default='待处理', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '安全隐患',
                'verbose_name_plural': '安全隐患',
                'db_table': 'safety_alerts',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('country', models.CharField(blank=True, default='中国', max_length=100, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='省份/州')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='最后登录IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='回复内容')),
                ('status', models.CharField(default='待回复', max_length=20, verbose_name='状态')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否屏蔽')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '留言反馈',
                'verbose_name_plural': '留言反馈',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.message', verbose_name='留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '留言评论',
                'verbose_name_plural': '留言评论',
                'db_table': 'message_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='地区')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('tourist_count', models.FloatField(verbose_name='游客数量(万人次)')),
                ('revenue', models.FloatField(verbose_name='营收(万元)')),
                ('flight_count', models.IntegerField(verbose_name='航班次数')),
                ('aircraft_count', models.IntegerField(verbose_name='航空器数量')),
                ('growth_rate', models.FloatField(verbose_name='增长率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '统计数据',
                'verbose_name_plural': '统计数据',
                'db_table': 'statistics',
                'ordering': ['-year', 'region'],
                'unique_together': {('region', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MessageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.message', verbose_name='留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '留言点赞',
                'verbose_name_plural': '留言点赞',
                'db_table': 'message_likes',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
