# Generated by Django 6.0.2 on 2026-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicache',
            name='normalized_question',
            field=models.TextField(blank=True, help_text='用于提高语义匹配命中率', null=True, verbose_name='标准化后的问题'),
        ),
        migrations.AddIndex(
            model_name='aicache',
            index=models.Index(fields=['normalized_question'], name='ai_cache_normali_7ab57d_idx'),
        ),
    ]
