# Generated by Django 6.0.2 on 2026-04-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['sort_order', '-is_hot', '-rating', '-views', '-created_at'], 'verbose_name': '旅游目的地', 'verbose_name_plural': '旅游目的地'},
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(db_index=True, default='北京', max_length=100, verbose_name='所属城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='首页推荐'),
        ),
        migrations.AddField(
            model_name='destination',
            name='recommendation_type',
            field=models.CharField(choices=[('nearby', 'IP周边推荐'), ('managed', '管理员推荐')], default='managed', max_length=20, verbose_name='推荐类型'),
        ),
        migrations.AddField(
            model_name='destination',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序值'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='cover_image',
            field=models.ImageField(upload_to='media-destination/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='messagecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
