# Generated by Django 4.2 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='文件哈希值(SHA256)')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件存储路径')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME类型')),
                ('reference_count', models.IntegerField(default=0, verbose_name='引用次数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '媒体文件',
                'verbose_name_plural': '媒体文件',
                'db_table': 'media_files',
                'ordering': ['-created_at'],
            },
        ),
    ]