# Generated by Django 6.0.2 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='中国', max_length=100, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省份/州'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='最后登录IP'),
        ),
    ]
