# Generated by Django 6.0.2 on 2026-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_username_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='用于最新发布排序，留空则使用创建时间', null=True, verbose_name='发布日期'),
        ),
    ]
