# Generated by Django 6.0.2 on 2026-04-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_destination_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, default='中国', max_length=100, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省份/州'),
        ),
    ]
