# Generated by Django 6.0.2 on 2026-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_destination_country_destination_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_domestic',
            field=models.BooleanField(default=True, verbose_name='是否国内'),
        ),
    ]
